config/routes.rb
Rails.application.routes.draw do
  resources :exercises, :workouts, :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root 'static_pages#home'
  get '/about'		=> 	'static_pages#about'
  get '/contact'     	=>	'static_pages#contact'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :date, presence: true
  
  belongs_to :user
  has_many :exercise_records, dependent: :destroy
  has_many :exercise_sets, through: :exercise_records
  accepts_nested_attributes_for :exercise_records, :reject_if => :all_blank, :allow_destroy => true
  
  #exercises included in the workout (string)
  def exercises
    ids = self.exercise_records.pluck(:exercise_id)
    Exercise.where(id: ids)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = current_user.workouts.order(date: :desc)
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = current_user.workouts.build
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = current_user.workouts.build(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end
    
    def correct_user
      redirect_to(root_url) if current_user != @workout.user
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:date, :notes,
        :exercise_records_attributes => [:id, :exercise_id, :workout_id, :_destroy,
          :exercise_sets_attributes => [:id, :reps, :weight, :_destroy] ]
        )
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def exercises_with_links(exercises)
    exercises.map {|x| link_to(x.name, x)}.join(', ').html_safe
  end
end

app/views/workouts/_exercise_record_fields.html.erb
<div class='form-inline exercise-record nested-fields well'>
  <%= f.association :exercise, wrapper_html: { class: 'exercise-field'} %>
  
  <%= link_to_remove_association f , class: 'btn btn-danger btn-xs', :data => {:confirm => 'do you really want to do this?'} do %>
    <i class="fa fa-times"></i>
  <% end %>
  <div class="sets nested-fields">
    <%= f.simple_fields_for :exercise_sets do |exercise_set| %>
      <%= render 'exercise_set_fields', :f => exercise_set %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add a set', f, :exercise_sets, class: 'btn btn-default btn-xs' %>
    </div>
  </div>
</div>

app/views/workouts/_exercise_set_fields.html.erb
<div class='nested-fields form-inline set'>
    <%= f.input :weight, wrapper_html: { class: 'set-field'} %>
    <%= f.input :reps, wrapper_html: { class: 'set-field'}  %>
    <%= link_to_remove_association  f, class: 'btn btn-danger btn-xs' do %>
        <i class="fa fa-times"></i>
    <% end %>
</div>

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout) do |f| %>
  <%= f.input :date, as: :string %>
  <%= f.input :notes %>
  <h3>Exercises</h3>
  <div id="exercises">
    <%= f.simple_fields_for :exercise_records do |exercise_record| %>
      <%= render 'exercise_record_fields', :f => exercise_record %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add exercise', f, :exercise_records, class: 'btn btn-primary btn-xs' %>
    </div>
  </div>
  <%= f.button :submit, class: 'btn btn-success'%>
<% end %>

app/views/workouts/edit.html.erb
<% provide(:title, "Edit Workout") %>
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<% provide(:title, "Workouts") %>
<%- model_class = Workout -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <p>Your workouts.</p>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_workout_path,
            :class => 'btn btn-primary' %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th>Exercises</th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= link_to workout.date, workout_path(workout) %></td>
        <td><%= exercises_with_links(workout.exercises) %></td>
        <td><%= link_to workout.notes, workout_path(workout) %></td>
        <td>
          <%= link_to "Show", workout_path(workout), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_workout_path(workout), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      workout_path(workout),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workouts/new.html.erb
<% provide(:title, "New Workout") %>
<h1>New Workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<% provide(:title, "Workout") %>
<h1><%= @workout.date %></h1>
<div>
  <p>Notes:</p>
  <blockquote>
    <p><%= @workout.notes %></p>
  </blockquote>
  <% @workout.exercise_records.each do |record| %>
    <div class="panel panel-default">
      <div class="panel-heading"><span class="h4"><%= record.exercise.name %></span> <span class="pull-right">volume: <%= record.volume %> </span></div>
      <table class="table table-hover">
        <tr>
          <th>
            Weight (max: <%= record.max_weight_set.weight if record.max_weight_set %> )
          </th>
          <th>
            Reps (total: <%= record.total_reps %> )
          </th>
        </tr>
        <% record.exercise_sets.each do |set| %>
          <tr>
            <td>
              <%= set.weight %>
            </td>
            <td>
              <%= set.reps %>
            </td>
          </tr>
        <% end %>
      </table>  
    </div>
  <% end %>
</div>
<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>