config/routes.rb
Rails.application.routes.draw do
  resources :exercises, :workouts, :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root 'static_pages#home'
  get '/about'		=> 	'static_pages#about'
  get '/contact'     	=>	'static_pages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :workouts, dependent: :destroy
  has_many :exercise_records, through: :workouts
  has_many :exercise_sets, through: :exercise_records
  
  
  def personal_record(exercise)
    records = self.exercise_records.where(exercise_id: exercise).pluck(:id)
    max_set = ExerciseSet.where(exercise_record_id: records).order("weight DESC, reps DESC").first
    return max_set
  end
  
  def all_prs()
    exercises_ids = self.exercise_records.pluck("DISTINCT exercise_id")
    exercises_ids.map { |id| self.personal_record(id) }
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # GET /users
  def index
    @users = User.all
  end
  
  # GET /workouts/1
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <p>All users</p>
</div>
<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= link_to user.email, user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% provide(:title, @user.email ) %>
<%- model_class = User -%>
<div class="page-header">
  <h1><%=@user.email %></h1>
</div>

<dl class="dl-horizontal">
  <p>Hello this user is pretty cool</p>
</dl>

<div class="panel panel-default">
  <div class="panel-heading"><span class="h4">PRs</span></div>
  <table class="table">
    <tr>
      <th>Exercise</th>
      <th>Weight</th>
      <th>Reps</th>
      <th>Date</th>
    </tr>
    <% @user.all_prs.each do |pr| %>
      <tr>
        <td><%= link_to(pr.exercise.name, exercise_path(pr.exercise)) %></td>
        <td><%= pr.weight %></td>
        <td><%= pr.reps %></td>
        <td><%= link_to(pr.workout.date, workout_path(pr.workout)) %></td>
      </tr>
    <% end %>
  </table>
</div>


<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>