config/routes.rb
Rails.application.routes.draw do
  resources :exercises, :workouts, :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root 'static_pages#home'
  get '/about'		=> 	'static_pages#about'
  get '/contact'     	=>	'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer>
  &copy; Sashuha  & Liron
  <ul class="nav pull-right">
    <%= link_to 'Home', root_path %>
    <%= link_to 'About', about_path %>
    <%= link_to 'Contact', contact_path %>
  </ul>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Exercise Log</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>>ExerciseLog</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%= nav_link 'Workouts', workouts_path %>
	        <%= nav_link 'Exercises', exercises_path %>
	        <%= nav_link 'Users', users_path %>
        </ul>
	<ul class="nav navbar-nav navbar-right">
	  <%= render 'devise/menu/registration_items' %>
	  <%= render 'devise/menu/login_items' %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navbar -->

  <div class="container">
    <%= bootstrap_flash %>
    <%= yield %>
    <hr>
    <%= render "/layouts/footer" %>
  </div>
</body>
</html>